### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by ripper234** [groupwrite-io/groupwrite.io#16]
Look for various values which are inline in the server code, and move them to a common config file.

Look for `// TODO Config` in the code (not all values that need to move are labeled as such)

(Sample config layout from https://github.com/madhums/node-express-mongoose-demo)

**Comment by DorWeid** [comment]
On it

**Comment by DorWeid** [comment]
#42 for a start

**Comment by ripper234** [comment]
Done for now, closing.
